### ISSUE TITLE
Ignore generated book/**

### ISSUE THREAD

**Issue by overvenus** [tikv/deep-dive-tikv#10]
Maybe we should ignore `book/**` on master branch, they are generated by mdbook. By ingoring `book/**` we can fouce on reviewing articles and avoid git repo bloat.

We can publish `book/**` to a new branch, eg, gh-pages.

**Comment by siddontang** [comment]
@overvenus 

Now the Github pages support generating from the master branch directly. Seem other projects like Rust doc also use this way with mdbook.

**Comment by overvenus** [comment]
We can take a look at https://github.com/rust-lang/book. It holds generated htmls in `gh-pages`.

**Comment by siddontang** [comment]
PTAL @Hoverbear

**Comment by Hoverbear** [comment]
@overvenus Do you think trying to set up a CI script to automatically push a new version to gh-pages on each push to master is a worthwhile effort? I worry that people will forget to push to gh-pages. :(

**Comment by siddontang** [comment]
@Hoverbear 

I think a githook can solve this problem, like https://gist.github.com/dsferruzza/a29e46123423dc46f57e

**Comment by Hoverbear** [comment]
Oh, yes, that would work. Do we have a machine we can have do this?

**Comment by siddontang** [comment]
@Hoverbear what machine?

**Comment by Hoverbear** [comment]
@siddontang To run the git hook.

**Comment by siddontang** [comment]
I don't know why you need a machine?
the git hook will be triggered when you commit in your local machine.

**Comment by Hoverbear** [comment]
But it needs to run on merge, which is done by the button on Github.

**Comment by siddontang** [comment]
We can write a bot to listen to the merge hook (or we can even update the master regular like daily) and generate the gh-pages automatically. 

We have some cloud machines, you can use them directly.

**Comment by Hoverbear** [comment]
Oh, I have an idea. We can use Travis-CI to build and push to a `gh-pages` branch whenever master is merged.

**Comment by Hoverbear** [comment]
I'll try the process here: https://takuti.me/note/travis-gh-pages-deployment/
