### ISSUE TITLE
Use mdbook?

### ISSUE THREAD

**Issue by Hoverbear** [tikv/deep-dive-tikv#3]
Seems https://github.com/rust-lang-nursery/mdBook is a nice alternative to Gitbook in Rust.

**Comment by ice1000** [comment]
I'd rather recommend to create `tikv.github.io`.

I can help with Jekyll website building and local environment building -- I've been working with Jekyll for long (I'm not proficient in frontend dev, tho).

**Comment by siddontang** [comment]
thanks @ice1000 

But this is not for TiKV webpage, and @ceohockey60 has been planning to make it. 
We can add a link to this repo later.

**Comment by Hoverbear** [comment]
@ice1000 I expect this will be one of many books. :)

Maybe something like a `books` repo so the Github pages would be at `tikv.github.io/books/head-first` or `tikv.github.io/books/design-patterns` etc?

And yes, I know from @ceohockey60 that we're currently in the process of rolling out a dedicated TiKV site. (How exciting.) I'd rather see us something like https://www.getgutenberg.io/ than Jekyll, so we don't need to care about tooling and environment.

**Comment by ice1000** [comment]
> Maybe something like a books repo so the Github pages would be at tikv.github.io/books/head-first or tikv.github.io/books/design-patterns etc?

Yeah, you can have `gh-pages` branch in non-`tikv.github.io` projects.

**Comment by ice1000** [comment]
Jekyll is natively supported by GitHub, this is why I just mentioned it. Use your best choice anyway :)

**Comment by Hoverbear** [comment]
You can map it to non gh-pages branches too. Eg #4 would rely on it being on master anyways. :)
